<script>
  import { Label, Heading } from "flowbite-svelte";
  import { Select} from 'flowbite-svelte'

  let selected;
    let Target_Genome=[
				{value:"human", name:"Homo sapiens (GRCh38/hg38) - Human"},
				{value:"human1", name:"Homo sapiens (hg19) - Human"},
				{value: "Pepper", name: "Pepper"},
				{value: "Dempsey", name: "Dempsey"},
				{value:"mm10", name:"Mus musculus (mm10) - Mouse"},
				{value:"bosTau7",name:"Bos taurus (bosTau7) - Cow"},
				{value:"canFam3", name: "Canis familiaris (canFam3) - Dog"},
				{value:"rn5", name: "Rattus norvegicus (rn5) - Rat"},
				{value:"susScr11", name: "Sus scrofa (susScr11) - Pig"},
				{value:"danRer7", name: "Danio rerio (danRer7) - Zebrafish"},
				{value:"rheMac3",name: "Macaca mulatta(rheMac3) - Monkey"},
				{value:"JGI42", name: "Xenopus tropicalis (JGI 4.2/xenTro3) - Western clawed frog"},
				{value:"JGI71", name: "Xenopus tropicalis (JGI 7.1) - Western clawed frog"},
				{value:"JGI71A",name: "Xenopus laevis (JGI 7.1) - African clawed frog"},
				{value:"Cv10", name: "Cricetulus griseus (v1.0) - Chinese Hamster"},
				{value:"JGI80", name: "Xenopus tropicalis (JGI 8.0) - Western clawed frog"},
				{value:"JGI90", name: "Xenopus tropicalis (JGI 9.0) - Western clawed frog"},
				{value:"JGI91", name: "Xenopus laevis (JGI 9.1) - African clawed frog"},
				{value:"macaca50", name: "Macaca fascicularis (5.0) - Crab-eating macaque"},
				{value:"GRCz10", name: "Danio rerio (GRCz10) - Zebrafish"},
				{value: "Rnor60", name: "Rattus norvegicus (Rnor 6.0) - Rat"},
				{value:"EquCab2", name: "Equus caballus (EquCab2) - Horse"},
				{value: "OryCun2", name: "Oryctolagus cuniculus (OryCun2) - Rabbit"},
				{value: "MesAur10", name: "Mesocricetus auratus (MesAur1.0) - Golden hamster"},
				{value:"Felis62", name: "Felis catus (6.2) - Cat"},
				{value:"AHZW01", name: "Mochrtus ochrogaster (AHZW01) - Prairie vole"},
				{value:"bosTau8", name: "Bos taurus (bosTau8) - Cow"},
				{value: "calJac3", name: "Callithrix jacchus (calJac3) -marmoset"},
				{value:"SOAPdenovov2", name: "Pimephales promelas (SOAPdenovo v. 2) - fathead minnow"},
				{value: "Oarv31", name: "ovis_aries (Oar_v3.1) - sheep"},
				{value: "AQIB01", name: "Chlorocebus_sabeus (AQIB01) - green monkey"},
				{value:"Galga14", name: "Gallus gallus (Galgal4) - Chicken"},
				{value:"ASM1858804v2",name: "Oreochromis niloticus (ASM185804v2)"},
				{value: "ARS1", name: "Capra hircus (ARS1) - goat"},
				{value: "Pman10", name: "Peromyscus maniculatus (Pman_1.0) - North American deer mouse"},
				{value: "Muml801", name: "Macaca mulatta (Mmul_8.0.1) - Monkey"},
				{value: "CriGri10", name: "Cricetulus griseus (CriGri_1.0) - Chinese hamster"},
				{value: "Cavpor30", name: "Cavia porcellus (Cavpor3.0) -guinea pig"},
				{value:"GRCz11", name: "Danio rerio (GRCz11) - zebrafish"},
				{value: "mm9", name: "Mus musculus (mm9) - Mouse"},
				{value: "BGIduk10", name: "Anas platyrhynchos (BGI_duck_1.0) - duck"},
				{value: "Gallus50", name: "Gallus gallus (Gallus_gallus-5.0) - Chicken"},
				{value:"ICSASGv2",name: "Salmo salar (ICSASG_v2) -Atlantic salmon"},
				{value: "commoncarp", name: "Cyprinus carpio (common carp genome)"},
				{vaule: "Otshv10", name: "Oncorhynchus tshawytscha (Otsh_v1.0) - Chinook salmon"},
				{value: "NC012920", name: "Human Mitochondria genome (NC_012920.1)"},
				{value:"AJ512208", name: "BalbC/J mouse Mitochondria genome (AJ512208.1)"},
				{value: "ARSUCD12", name: "Bos taurus (ARS UCD1.2)"},
				{value: "Flounderrefguidedv10", name: "Paralichthys olivaceus (Flounder_ref_guided_V1.0)"},
				{value:"Myoluc20",name: "Myotis lucifugus (Myoluc2.0)"},
				{value:"Raegyp20",name: "Rousettus aegyptiacus (Raegyp2.0)"},
				{value:"TS20longread",name: "Tree shrew (TS_20 long-read)"},
				{value:"ASM291563v2", name: "Ambystoma mexicanum (ASM291563v2) -axolotl"},
				{value:"GRCg6a", name: "Gallus gallus (GRCg6a) - chicken"},
				{value: "IPCoco12", name: "Ictalurus punctatus (IpCoco_1.2)"},
				{value:"Musputfur10", name: "Mustela putorius furo (MusPutFur1.0) - Ferret"},
				{value: "GCF0002967551", name: "Erinaceus_europaeus (GCF_000296755.1)"},
				{value:"Mmul10",name: "Macaca mulatta (Mmul_10)"},
				{value: "Macacafascicularis50", name: "Macaca fascicularis (Macaca_fascicularis_5.0)"},
				{value: "Pmaj10", name: "Pagrus major (Pmaj_1.0)"},
				{value: "Petromyzon", name: "Petromyzon_marinus"},
				{value: "CHM13T2Tv11",name: "Homo sapiens (CHM13 T2T v1.1) - Human"},
				{value: "ARSUIRambv20",name: "Ovis aries (ARS-UI_Ramb_v2.0) - Sheep"},
				{value: "EquCab30",name: "Equus caballus (EquCab3.0) - horse"},
				{value: "Epinephelus",name: "Epinephelus coioides () - Orange-spotted grouper"},
				{value: "fAnaTes12",name: "Anabas testudineus (fAnaTes1.2) - Climbing perch"},
				{value: "NDDBSH1",name: "Bubalus bubalis (NDDB_SH_1)"},
				{value: "Largewhitev1",name: "Sus scrofa (Large white v1 from ensembl) - pig"},
				{value: "T2TCHM13v2",name: "Homo sapiens (T2T_CHM13v2) - Human"},
				{value: "USDANASsal11",name: "Salmo salar (USDA_NASsal_1.1) - Atlantic salmon"},
				{value: "ASM1834538v1",name: "Vulpes lagopus (ASM1834538v1) - Arctic fox"},
				{value: "fTakRub13",name: "Takifugu rubripes (fTakRub1.3 from ENA)"},
				{value: "Mnem10",name: "Macaca nemestrina (Mnem_1.0)"},
				{value: "EptFus10", name: "Eptesicus fuscus (EptFus1.0) - Big brown bat"},
				{value: "USDAOmykA11",name: "Oncorhynchus mykiss (USDA_OmykA_1.1) - rainbow trout"},
				{value: "ASM32557v1",name: "Pteropus alecto (ASM32557v1) - Black flying fox"},
				{value: "Macaca60",name: "Macaca fascicularis (6.0) - Crab-eating macaque"},
				{value: "Europeanseabass",name: "Dicentrarchus labrax - (European seabass)"},
				{value: "ASM1607732v2",name: "Equus asinus (ASM1607732v2) - Ass"},
				{value: "GRCm39", name: "GRCm39/mm39- mouse"},

]
	</script>
	<div class="mb-2">
		<Label for="label"  size="lg" >Select organism type 
			<Select   size="lg" id="label" items={Target_Genome} class=" cursor-pointer flex-shrink-0 z-10 inline-flex py-2.5 px-4 items-center text-md font-medium text-left text-gray-500 bg-gray-100 border border-gray-300 rounded-l-lg hover:bg-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 dark:focus:ring-gray-700 dark:text-white dark:border-gray-600" bind:value={selected} />
		  </Label>
	</div>